### ISSUE TITLE
npm is not installed

### ISSUE THREAD

**Issue by MuchZakariya** [mukhlisakbr/node-whatsapp-sticker-bot#1]
Npm warn home no description dll

**Comment by mukhlisakbr** [comment]
it's not a problem but just a warning

**Comment by MuchZakariya** [comment]
![Screenshot_2020-08-02-07-45-09-048_com termux](https://user-images.githubusercontent.com/39432451/89112899-37860600-d494-11ea-9084-9640fb08c33b.png)
![Screenshot_2020-08-02-07-45-21-468_com termux](https://user-images.githubusercontent.com/39432451/89112908-44a2f500-d494-11ea-9f2e-6899da1ecdf4.png)
![Screenshot_2020-08-02-07-45-38-175_com termux](https://user-images.githubusercontent.com/39432451/89112909-48cf1280-d494-11ea-98bc-8424ab1971fb.png)
what's the solution? when I try to install npm the problem always appears

**Comment by MuchZakariya** [comment]
![Screenshot_2020-08-02-07-44-59-896_com termux](https://user-images.githubusercontent.com/39432451/89112932-99df0680-d494-11ea-9a33-84c015855654.png)

**Comment by mukhlisakbr** [comment]
did you try it on termux?

**Comment by MuchZakariya** [comment]
Yes, i'm try on termux

**Comment by mukhlisakbr** [comment]
I don't recommend it even though it actually works if you can install the node as recommended by the lts version 12.8.3, and there must also be python because "Termux" doesn't have it so all packages can't be built and installed properly.
